apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ok4j0zqsx-python
  janus-idp.io/tekton: ok4j0zqsx-python
  backstage.io/kubernetes-id: ok4j0zqsx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ok4j0zqsx-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
