apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ok4j0zqsx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ok4j0zqsx-python 
  name: ok4j0zqsx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ok4j0zqsx-python 
